FROM ruby:3.2.2-alpine

WORKDIR /app
COPY . .
ENV BUNDLER_WITHOUT="development test"

RUN apk update
RUN apk add git
RUN apk add --no-cache build-base

RUN gem install bundler
RUN gem install date
RUN bundle install -V

CMD ["bundle", "exec", "sidekiq"]
