FROM ruby:3.2.2-alpine

WORKDIR /app
COPY . .
ENV BUNDLER_WITHOUT="development test"

RUN apk update
RUN apk add git
RUN apk add --no-cache build-base
RUN apk add postgresql-dev

RUN gem install bundler:2.4.2
RUN bundle _2.4.2_ install -V

CMD ["bundle", "exec", "sidekiq"]
